### ISSUE TITLE
how did you change command bar identity level

### ISSUE THREAD

**Issue by dangerrxf** [Pseudoreality/Roblox-Identities#2]
i read the other issue and i still cannot find where to change them

**Comment by Hylician** [comment]
Same

**Comment by semiyan** [comment]
patched internal studio: https://github.com/7ap/internal-studio-patcher

**Comment by dangerrxf** [comment]
like a year late reply but i meant how to change the identity level of the dropdown menu buttons

**Comment by Pseudoreality** [comment]
> like a year late reply but i meant how to change the identity level of the dropdown menu buttons

They've changed how the CommandBar behaves in studio so I'm not sure how to do this anymore. If you somehow find yourself using an old version of Studio (sometime in Sep. 2023 and before I think?) then the old address for ElevatedStudioPlugin is showed in issue #3. The addresses for the other two are directly after ElevatedStudioPlugin's and are very similar to the address given.

If I get around to being able to change the identity on the newer CommandBar implementation then I'll probably update it here, depending on how tedious it is.
