### ISSUE TITLE
I was wondering how you do it?

### ISSUE THREAD

**Issue by 5h1b** [Pseudoreality/Roblox-Identities#3]
> You'd have to change out the three identities with a different number, which is assigned where the dropdown menu options are created. If you know the identity numbers, it's fairly easy to figure out which is which.
>
sorry for me replying to a old message, but i was wondering where is this located at? i want to change the identity level of ElevatedStudioPlugin from 6 to 7 (if i can do that without downloading something like [x64dbg](https://x64dbg.com/))
(I have [HxD](http://mh-nexus.de/hxd) if i need to edit any Hex.)

_Originally posted by @5h1b in https://github.com/Pseudoreality/Roblox-Identities/issues/1#issuecomment-2362706748_

This is a reply I made on the "[How hard is it?](https://github.com/Pseudoreality/Roblox-Identities/issues/1)" issue, I'm just making this issue so that you can see it, since I didn't know if you seen the reply.

**Comment by Pseudoreality** [comment]
This address might be a little wrong since I have a longer version of the string that's mostly wildcards but I think I got the base, non-wildcard version of the string that only changes the identity level. The version I used is the current version (v644 as of writing) so it may or may not work on previous/future versions, depending on how the bytes change.

Anyway, the string is `EF C7 45 F7 06`. You would change the `06` to a `07`.
As said before though, this might only be a temporary solution.

**Comment by 5h1b** [comment]
thank you, it worked

**Comment by oofman124** [comment]
@Pseudoreality Almost a year later, I think Roblox patched how to edit the identity level. I couldn't find ```EF C7 45 F7 06``` when editing RobloxStudioBeta.exe with HxD. Any workarounds? (sorry for the late reply)

**Comment by oofman124** [comment]
Also, I have a friend of mine that obtained Roblox Studio Internal legitimately (it has a level 7 command bar). Would you like the version folder of that?

**Comment by Playerr10** [comment]
@oofman124 | @Pseudoreality, You're correct about Roblox patching the way to elevate your identity. I think before version <650? (this is an estimate), I used to be able to modify the assembly code (using x64dbg) in where ElevatedStudioPlugin was located and modified a value that was 0x06 -> 0x08 to have a identity of 8 (WebService) using **printidentity()** in the command-bar. Sadly, I cant really find a way to elevate this back to identity level 8 like how I did almost a year ago. If anybody has a solution, please comment down below! :D

**Comment by oofman124** [comment]
@Playerr10  I compared the RobloxStudioBeta.exe files (my regular one vs my friend's one with internal), and they have the same binary data.
Also, in the dropdown for the command bar in internal studio, my friend told me that he saw 4 options: ElevatedStudioPlugin, CommandBar, GameScript, and most importantly, **Roblox** (level 7/8)

**Comment by kieldbg** [comment]
Hey there @Playerr10 @oofman124, did y'all manage to find a way to elevate the command bar's identity to 8? 

And @Pseudoreality, are you aware of any ways to do so, that currently works in the latest versions of studio?

Thanks a lot!

**Comment by oofman124** [comment]
@0x1437 I wasn’t able to figure out how to get a level 8 command bar, but I did manage to find a method for running level 7 Luau code. For now, this seems like the only option. It works through an external tool called **RbxStu**, which takes advantage of the fact that Studio doesn’t have an anticheat.

Here's the repo: [github.com/RbxStu/RbxStu](https://github.com/RbxStu/RbxStu)

**Comment by oofman124** [comment]
@0x1437 Sorry, the link I sent was to the oldest version of RbxStu. This Roblox devforum post should have it:

https://devforum.roblox.com/t/rbxstu-v4-roblox-studio-luau-api-modification/3642087

Here's their discord: https://discord.gg/Xj3ffmahJd



_Not sponsored!_

**Comment by 0x1437** [comment]
> [@0x1437](https://github.com/0x1437) Sorry, the link I sent was to the oldest version of RbxStu. This Roblox devforum post should have it:
> 
> https://devforum.roblox.com/t/rbxstu-v4-roblox-studio-luau-api-modification/3642087
> 
> Here's their discord: https://discord.gg/Xj3ffmahJd
> 
> _Not sponsored!_

Unfortunately, this is not viable for my use case. I am needing to achieve execution with identity 7/8 before play testing, which is not supported by RbxStu.

<img width="1920" height="1023" alt="Image" src="https://github.com/user-attachments/assets/a385e165-b019-45b9-acc3-714390136da4" />
